project: "iapytoo"
run: "infer"
tracking_uri: /work/lecomtje/Repositories/iapy/iapytoo/mlruns

dataset:
  path: "../data"
  n_steps_by_batch: 10
  num_workers: 2
  batch_size: 64
 
metrics:
  names: ['accuracy']
model:
  type: "mlflow"
  run_id: "eb22ed3db7064e0c8c4513e4ac26486b"
