project: "iapytoo"
run: "infer"
tracking_uri: null

dataset:
  path: "../data"
  n_steps_by_batch: 10
  num_workers: 2
  batch_size: 64
 
metrics:
  names: ['accuracy', 'r2']

model:
  type: "mlflow"
  predictor: "max"
  run_id: "59606474825b41b68b536f80d0b1911e"