project: wgan
run: wgan
tracking_uri: null

dataset:
  path: "./data"
  n_steps_by_batch: 10
  num_workers: 2
  batch_size: 256

training:
  learning_rate: 0.0002
  optimizer: adam
  scheduler: step
  gamma: 0.7
  # betas:
  #   - 0.5
  #   - 0.99
  epochs: 11
  loss: "wasserstein"

model:
  model: "gan"
  generator: generator
  discriminator: critic
  n_critic: 1
  lambda_gp: 10
  noise_dim: 100
