project: "iapytoo"
run: "infer"
tracking_uri: "./mlruns"

dataset:
  path: "../data"
  n_steps_by_batch: 10
  num_workers: 2
  batch_size: 64
 
metrics:
  names: ['accuracy', 'r2']

model:
  type: "mlflow"
  provider: "MnistProvider"
  run_id: "5ed6c950d260451f89cb08b6f61529f4"